### PR TITLE
784 update onboarding docs

### PR DESCRIPTION
**Pull request by lewisdaly**
Part of: https://github.com/mojaloop/project/issues/784

This is the first part of consolidating the Onboarding documentation across a number of sub-projects. The windows installation steps are incomplete (I don't have access to a windows machine), and I still need to double check the Linux installation steps.

I'm mainly looking for some feedback before I go too much further - so feel free to to tear this to shreds.

You can view the rendered `.md` file here: https://github.com/vessels-tech/mojaloop/blob/784-update-onboarding-docs/onboarding.md

### CODE REVIEW

**Comment by elnyry** [comment]
@lewisdaly thanks for doing this. 

It mostly looks fine but the development workflow needs changes. Please review this doc - https://github.com/mojaloop/documentation/blob/master/contributors-guide/standards/creating-new-features.md  for the PR process we use (which you know very well :-) )..

**Comment by lewisdaly** [comment]
@elnyry done. Thanks for the feedback.

**Comment by elnyry** [comment]
One minor suggestion as well, will leave it to you and approve as well..

Can you please also number the initial list?

**Comment by lewisdaly** [comment]
> One minor suggestion as well, will leave it to you and approve as well..
> 
> Can you please also number the initial list?

Sure, no problem.

**Pull request merged**
